name: dissent
base: core24
adopt-info: main
summary:  GTK4 Discord client in Go
description: |
    GTK4 Discord client in Go

    Source: https://github.com/diamondburned/dissent
    Snap-Source: https://github.com/nbuechner/dissent-snap

grade: stable
confinement: strict

platforms:
  amd64:
    build-on: amd64
    build-for: amd64
  arm64:
    build-on: arm64
    build-for: arm64

slots:
   dbus-dissent:
      interface: dbus
      bus: session
      name: so.libdb.dissent
apps:
  dissent:
    command-chain: ["./check.sh"]
    command: bin/dissent
    desktop: share/applications/so.libdb.dissent.desktop
    plugs: [home, x11, desktop, network, removable-media, password-manager-service ]
    slots: [ dbus-dissent ]
    extensions: [ gnome ]

  dissent-dbus:
    desktop: share/applications/dissent-dbus.desktop
    command: bin/dissent --gapplication-service
    extensions: [ gnome ]
    slots: [ dbus-dissent ]
    daemon: simple

parts:
  main:
    override-pull: |
         MYARCH="amd64"
         if [ $(uname -i) == 'aarch64' ]; then
            MYARCH="arm64"
         fi
         version=$(wget -qO- https://api.github.com/repos/diamondburned/dissent/releases/latest | jq -r '.tag_name' | cut -c2-)
         wget -O release.tar.zst https://github.com/diamondburned/dissent/releases/download/v$version/dissent-linux-${MYARCH}.tar.zst
         tar xf release.tar.zst
         rm -f release.tar.zst
         sed -i -e 's|Icon=so.libdb.dissent|Icon=share/icons/hicolor/scalable/apps/so.libdb.dissent.svg|g' share/applications/so.libdb.dissent.desktop
         sed -i -e 's|Exec=dissent|Exec=dissent.dissent|g' share/applications/so.libdb.dissent.desktop
         cp -f ${CRAFT_PROJECT_DIR}/snap/gui/dissent-dbus.desktop share/applications/dissent-dbus.desktop
         cp -f ${CRAFT_PROJECT_DIR}/local/check.sh $SNAPCRAFT_PART_INSTALL/check.sh
         chmod a+rx $SNAPCRAFT_PART_INSTALL/check.sh
         craftctl set version="$version"
         craftctl default
    source: .
    plugin: dump
    source-type: local
    stage-packages:
      - whiptail
      - libgtksourceview-5-0
      - libspelling-1-1
    build-packages:
      - wget
      - zstd
      - jq

layout:
  /usr/share/applications:
    bind: $SNAP/share/applications
  /usr/share/icons:
    bind: $SNAP/share/icons

lint:
  ignore:
    - library
