name: gtkcord4-unofficial
base: core22
version: '0.0.10'
summary: GTK4 Discord client in Go
description: |
    A GTK4 Discord client in Go

    This is not an official build.

    Source: https://github.com/diamondburned/gtkcord4
    Snap-Source: https://github.com/nbuechner/gtkcord4-snap

grade: stable
confinement: strict
architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: arm64
    build-for: arm64

slots:
   dbus-gtkcord4:
      interface: dbus
      bus: session
      name: xyz.diamondb.gtkcord4

apps:
  gtkcord4-unofficial:
    command: bin/gtkcord4
    plugs: [home, x11, desktop, network ]
    extensions: [ gnome ]
    slots: [ dbus-gtkcord4 ]

parts:
  main:
    source: https://github.com/diamondburned/gtkcord4/archive/refs/tags/v0.0.10.tar.gz
    plugin: go
    override-prime: |
       craftctl default

    stage-packages:
      - desktop-file-utils

    build-snaps:
       - go
